### ISSUE TITLE
Add Maryam Yazdanparast

### ISSUE THREAD

**Issue by nekofar** [nekofar/awesome-freelancers#40]
<blockquote class="twitter-tweet"><p lang="fa" dir="rtl">مقاله ویرایش می‌کنم و رفع پلاجیاریسم<br>بیشتر هم حوزه‌های مرتبط با زیست</p>&mdash; یه پری خسته (@MParast) <a href="https://twitter.com/MParast/status/1179797263440400384?ref_src=twsrc%5Etfw">October 3, 2019</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

**Comment by sadeqn** [comment]
مریم برای نوشتن پایان‌نامه و مقاله به زبان فارسی و انگلیسی هم مشاوره می‌ده. 
حوزه کار تخصصی‌ش هم علوم زیستی و میکروبیولوژی است.
وبسایت کاری مریم https://hwlwk.ir است.
