### ISSUE TITLE
Add ǝɹɪuoɯ

### ISSUE THREAD

**Issue by nekofar** [nekofar/awesome-freelancers#74]
<blockquote class="twitter-tweet"><p lang="fa" dir="rtl">حوزه رو نمیدونم ولی حرفه‌م عکاسی‌ه. در تمامی شبکه‌های مجازی آی‌دی م <a href="https://twitter.com/moniirre?ref_src=twsrc%5Etfw">@moniirre</a> ست</p>&mdash; ǝɹɪuoɯ (@moniirre) <a href="https://twitter.com/moniirre/status/1181159546708008960?ref_src=twsrc%5Etfw">October 7, 2019</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

**Comment by sadeqn** [comment]
حرفه اصلی منیره عکاسی است اما می‌دونم در زمینه «تور عکاسی» هم فعالیت می‌کنه.
