### ISSUE TITLE
Add Mehdi

### ISSUE THREAD

**Issue by nekofar** [nekofar/awesome-freelancers#94]
<blockquote class="twitter-tweet" data-partner="tweetdeck"><p lang="en" dir="ltr">توسعه و طراحی وب<br>front-end:<br>web design(html, css)<br>js<br>back-end:<br>php (laravel)<br><br>mrmmg76@gmail.com<br><br>telegram: <a href="https://twitter.com/MrMMG?ref_src=twsrc%5Etfw">@mrmmg</a><a href="https://t.co/C6VxIAMQx8">https://t.co/C6VxIAMQx8</a></p>&mdash; •Mehdi• (@mrmehdi_gh) <a href="https://twitter.com/mrmehdi_gh/status/1181191230975348736?ref_src=twsrc%5Etfw">October 7, 2019</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

**Comment by mrmmg** [comment]
please check this pull requesr: #107
